# Generated by Django 3.2.7 on 2021-09-16 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("taxes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="amount",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="barcode",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="taxes.payable"
            ),
        ),
    ]
